config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.views import defaults as default_views

from sushibar.dashboard.views import DashboardView, RunView, open_channel_page
from sushibar.users.forms import SushiBarAuthenticationForm

urlpatterns = [
    # Dashboard web views
    url(r'^$', DashboardView.as_view(), name='home'),
    url(r'^saved/$', DashboardView.as_view(view_saved=True), name='saved'),
    # TODO: this is a bad regex, use a better one that matches UUID4
    url(r'^runs/(?P<runid>[0-9A-Fa-f-]+)/$', RunView.as_view(), name='runs'),
    url(r'^channelpage/(?P<channel>[0-9A-Fa-f]+)/$', open_channel_page, name='open_channel_page'),
    url(r'^channels/(?P<channelid>[0-9A-Fa-f-]+)/$', RunView.as_view(search_by_channel=True), name='runs_for_channel'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    url(r'^schedule/$', TemplateView.as_view(template_name='pages/schedule.html'), name='schedule'),

    # Django admin
    url(settings.ADMIN_URL, admin.site.urls),

    # Authentication and BarUser management
    url(r'^signin/$', auth_views.LoginView.as_view(
        template_name='auth/signin.html',
        authentication_form=SushiBarAuthenticationForm), name='sushibar_signin'),
    url(r'^signout/$', auth_views.LogoutView.as_view(template_name='auth/signed_out.html'), name='sushibar_signout'),
    url(r'^users/', include('sushibar.users.urls')),

    # SushiChef API endpoints
    url(r'^api/', include('sushibar.runs.urls')),

    # External Service API endpoints
    url(r'^services/trello/', include('sushibar.services.trello.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns
    if 'rest_framework_swagger' in settings.INSTALLED_APPS:
        from rest_framework_swagger.views import get_swagger_view
        schema_view = get_swagger_view(title='Sushi Bar API')

        urlpatterns += [
            url(r'^apidocs/$', schema_view)
        ]

sushibar/runs/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns

from .api import ContentChannelListCreate, ContentChannelDetail, RunsForContentChannelList
from .api import ContentChannelRunListCreate, ContentChannelRunDetail
from .api import ChannelRunStageListCreate
from .api import ChannelRunProgressEndpoints
from .api import ContentChannelSaveToProfile
from .api import ChannelControlEndpoints
from .api import ContentChannelDelete

urlpatterns = [
    url(regex=r'channels/$',
        view=ContentChannelListCreate.as_view(),
        name='list_details'),
    #
    url(regex=r'channels/(?P<channel_id>[0-9A-Fa-f-]+)/$',
        view=ContentChannelDetail.as_view(),
        name='channel_details'),
    #
    url(regex=r'channels/(?P<channel_id>[0-9A-Fa-f-]+)/runs/$',
        view=RunsForContentChannelList.as_view(),
        name='runs_for_channel'),
    #
    url(regex=r'channels/(?P<channel_id>[0-9A-Fa-f-]+)/save_to_profile/$',
        view=ContentChannelSaveToProfile.as_view(),
        name='save_channel_to_profile'),
    #
    url(regex=r'channels/(?P<channel_id>[0-9A-Fa-f-]+)/delete_channel/$',
        view=ContentChannelDelete.as_view(),
        name='delete_channel'),
    #
    url(regex=r'channels/(?P<channel_id>[0-9A-Fa-f-]+)/control/$',
        view=ChannelControlEndpoints.as_view(),
        name='channel_control'),
    #
    url(regex=r'channelruns/$',
        view=ContentChannelRunListCreate.as_view(),
        name='list_runs'),
    #
    url(regex=r'channelruns/(?P<run_id>[0-9A-Fa-f-]+)/$',
        view=ContentChannelRunDetail.as_view(),
        name='run_details'),
    #
    url(regex=r'channelruns/(?P<run_id>[0-9A-Fa-f-]+)/stages/$',
        view=ChannelRunStageListCreate.as_view(),
        name='list_run_stages'),
    #
    url(regex=r'channelruns/(?P<run_id>[0-9A-Fa-f-]+)/progress/$',
        view=ChannelRunProgressEndpoints.as_view(),
        name='run_progress'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

sushibar/services/trello/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns

from .api import (ContentChannelSaveTrelloUrl,
                  TrelloAddChecklistItem,
                  TrelloMoveToFeedbackList,
                  ContentChannelFlagForQA,
                  TrelloNotifyCardChange,
                  TrelloSendComment,
                  TrelloMoveToDoneList,
                  TrelloMoveToPublishList)

urlpatterns = [
    # Save Trello URL to channel
    url(regex=r'(?P<channel_id>[0-9A-Fa-f-]+)/save_trello_url/$',
        view=ContentChannelSaveTrelloUrl.as_view(),
        name='save_trello_url'),

    # Check card is on authorized board
    url(regex=r'(?P<channel_id>[0-9A-Fa-f-]+)/add_item/$',
        view=TrelloAddChecklistItem.as_view(),
        name='trello_add_checklist_item'),

   	# Move card to Feedback Needed list
    url(regex=r'(?P<channel_id>[0-9A-Fa-f-]+)/request_feedback/$',
        view=TrelloMoveToFeedbackList.as_view(),
        name='trello_request_feedback'),

   	# Move card to QA list and create QA sheet
    url(regex=r'(?P<channel_id>[0-9A-Fa-f-]+)/flag_for_qa/$',
        view=ContentChannelFlagForQA.as_view(),
        name='trello_flag_channel_for_qa'),

    # Move card to DONE list
    url(regex=r'(?P<channel_id>[0-9A-Fa-f-]+)/mark_as_done/$',
        view=TrelloMoveToDoneList.as_view(),
        name='trello_mark_channel_as_done'),

    # Move card to Publish list
    url(regex=r'(?P<channel_id>[0-9A-Fa-f-]+)/flag_for_publish/$',
        view=TrelloMoveToPublishList.as_view(),
        name='trello_flag_channel_for_publish'),

    # WEBHOOK: Notify user when QA is done
    url(regex=r'(?P<channel_id>[0-9A-Fa-f-]+)/card_moved/$',
        view=TrelloNotifyCardChange.as_view(),
        name='trello_notify_card_move'),

    # Send comment to Trello card
    url(regex=r'(?P<channel_id>[0-9A-Fa-f-]+)/send_comment/$',
        view=TrelloSendComment.as_view(),
        name='trello_send_comment'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

sushibar/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'  # For Django 2+


urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

sushibar/dashboard/views.py
from collections import defaultdict
from datetime import datetime, timedelta, timezone
import json
import re
import uuid

from channels import Group
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.db.models import Q, Max
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseRedirect
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.template import RequestContext
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import ensure_csrf_cookie
from django.views.generic.base import TemplateView
import redis

from sushibar.ccserverlib.services import ccserver_get_topic_tree, get_channel_status_bulk, activate_channel, ccserver_publish_channel
from sushibar.runs.models import ContentChannel, ContentChannelRun, ChannelRunStage
from sushibar.services.trello.api import trello_add_card_to_channel

from .forms import ChannelCreateForm


REDIS = redis.StrictRedis(host=settings.MMVP_REDIS_HOST,
                          port=settings.MMVP_REDIS_PORT,
                          db=settings.MMVP_REDIS_DB,
                          charset="utf-8",
                          decode_responses=True)


def open_channel_page(request, channel):
    channel = ContentChannel.objects.get(channel_id=uuid.UUID(channel))
    last_run = channel.get_last_run()
    return redirect('runs', last_run and last_run.run_id)

def deploy_channel(request, channelid):
    status, response = activate_channel(request.user, channelid)
    if status == "failure":
        return HttpResponseBadRequest(response)
    return HttpResponse(response)

def publish_channel(request, channelid):
    status, response = ccserver_publish_channel(request.user, channelid)
    if status == "failure":
        return HttpResponseBadRequest(response)
    return HttpResponse(response)

# DASHABOARD HELPERS ###########################################################

def get_status_pct(progress, failed):
    fmt_pct = lambda f: int(float(f) * 100)
    if failed:
        return 100
    if progress is None:
        return 0
    return fmt_pct(progress.get('progress', 0))

def fmt_cl_flags(run):
    if not run.extra_options:
        return ""
    return " ".join("--%s=%s" % (k, v) for k, v in run.extra_options.items())

def make_chef_link(chef_name):
    return re.sub(r'git:[\w\d]+$', 'git', chef_name).replace("git+ssh://git@", "https://")

def fmt_chef_name(chef_name):
    return re.sub(r'git:[\w\d]+$', 'git', chef_name).replace("github.com","").replace("https://", "").replace("git+ssh://git@", "")

def get_status_for_mapping(channel, mapping, run=None):
    mapping = mapping or {}
    return get_status(mapping.get(channel.channel_id.hex),  run=run)

def get_status(status, run=None, channel_id=None):
    STATUS = {
        "deleted": {
            "name": "Deleted",
            "helper": "Channel has been deleted",
        },
        "staged": {
            "name": "Needs Review",
            "helper": "Channel is currently staged",
            "actions": [
                {
                    "action_text": "Review Channel",
                    "url": run and "%s/channels/%s/staging" % (run.content_server, run.channel.channel_id.hex)
                }
            ]
        },
        "unpublished": {
            "name": "Needs Publishing",
            "helper": "Channel has unpublished updates",
        },
        "active": {
            "name": "Active",
            "helper": "Channel is active",
        },
        "building" : {
            "name": "Building...",
            "helper": "Building topic tree for this channel",
        },
    }
    return STATUS.get(status)


def get_bulk_status_mapping_for_channels_as_baruser(channels, baruser):
    """
    Makes "bulk requests" to Studio server to get channel status for all the
    channels we're about to display on the dashboard.
    Assumptions: baruser has access to
    """
    status_mapping = {}
    # Group requests based on the Studio instance that we need to query
    channels_by_studio_server = defaultdict(list)
    for channel in channels:
        last_run = channels.exists() and channel.get_last_run()
        if last_run:
            studio_server = last_run.content_server
            if studio_server:
                channels_by_studio_server[studio_server].append(channel)
    #
    # Do batchs requests for statuses from all Kolibri servers
    for studio_server, channels in channels_by_studio_server.items():
        if 'learningequality.org' in studio_server:
            print('Making bulk request to', studio_server)
            channel_ids = [c.channel_id.hex for c in channels]
            statuses_dict = get_channel_status_bulk(studio_server, baruser.cctoken, channel_ids)
            status_mapping.update(statuses_dict)
        else:
            print('Skipping bulk request to', studio_server)
    #
    return status_mapping




# DASHABOARD ###################################################################
class DashboardView(LoginRequiredMixin, TemplateView):

    template_name = "pages/home.html"
    view_saved = False

    @method_decorator(ensure_csrf_cookie)
    def get(self, request, *args, **kwargs):
        return super(DashboardView, self).get(request, *args, **kwargs)

    def post(self, request):
        # create a form instance and populate it with data from the request:
        form = ChannelCreateForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            if ContentChannel.objects.filter(channel_id=form.cleaned_data['channel_id']).exists():
                form.add_error('domain', 'Channel with domain and source ID already exists')
                return HttpResponse(json.dumps({
                    'success': False,
                    'html': render_to_string("create_channel_modal.html", {'form': form}),
                }))

            channel = ContentChannel(
                spec_sheet_url=form.cleaned_data['spec_sheet_url'],
                chef_repo_url=form.cleaned_data['chef_repo'],
                channel_id=form.cleaned_data['channel_id'],
                name=form.cleaned_data['name'],
                source_domain=form.cleaned_data['domain'],
                source_id=form.cleaned_data['source_id'],
            )
            trello_add_card_to_channel(request, channel, form.cleaned_data['trello_url'])
            return HttpResponse(json.dumps({
                'success': True,
                'redirect_url': '/channels/{}/'.format(channel.channel_id.hex)
            }))
        return HttpResponse(json.dumps({
            'success': False,
            'html': render_to_string("create_channel_modal.html", {'form': form}),
        }))


    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        context['form'] = ChannelCreateForm()
        context['channels'] = []

        channels = []
        if self.request.user.is_staff:
            channels = ContentChannel.objects.all()
        else:
            channel_ids = ContentChannelRun.objects\
                            .filter(Q(started_by_user_token=self.request.user.cctoken) | Q(channel__followers=self.request.user))\
                            .values_list('channel__id', flat=True).distinct()
            channels = ContentChannel.objects.filter(pk__in=channel_ids)

        channels = channels.annotate(last_run_date=Max('runs__modified_at')).order_by('-last_run_date')

        # Try to get channel status information from Kolibri Studio
        status_mapping = {}   # { "<channel_id>": "{{status_str}}", ... }
        try:
            status_mapping = get_bulk_status_mapping_for_channels_as_baruser(channels, self.request.user)
        except Exception as e:
            status_mapping = {}
            print('ERROR during get_bulk_status_mapping_for_channels_as_baruser, continuing...', e)

        # MAIN LOOP
        ########################################################################
        # TODO(arvnd): This can very easily be optimized by querying the runs table directly.
        for channel in channels:

            # Get the most recent run for the channel
            try:
                last_run = channel.runs.latest("created_at")
            except ContentChannelRun.DoesNotExist:
                print("No runs for channel %s " % channel.name, "continuing...")
                channel_data = {
                    "channel": channel.name,
                    "due_date": channel.due_date,
                    "id": channel.channel_id.hex,
                    "starred": self.request.user.is_authenticated and self.request.user.saved_channels.filter(channel_id=channel.channel_id).exists(),
                    "status": "New",
                    "spec_sheet_url": channel.spec_sheet_url,
                    "chef_repo_url": channel.chef_repo_url,
                }

                context['channels'].append(channel_data)

                continue

            try:
                last_event = last_run.events.latest("finished")
            except ChannelRunStage.DoesNotExist:
                print("No stages for run %s" % last_run.run_id.hex, "continuing...")
                continue

            progress = REDIS.hgetall(last_run.run_id.hex)
            total_duration = sum((event.duration for event in last_run.events.all()), timedelta())

            # Channels with errors are flagged in YELLLOW, channels with critical errors in RED
            logs = last_run.get_logs()
            failed = any(logs.get('critical'))
            warnings = any(logs.get('error'))

            # check if any daemonized chef is listening for control commands
            control_group = Group('control-' + channel.channel_id.hex)
            listeners = control_group.channel_layer.group_channels(control_group.name)

sushibar/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

sushibar/templates/base.html
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <link rel="shortcut icon" href="{% static 'images/sushi.png' %}">
  <title>{% block title %}Sushi Bar{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
      <![endif]-->

      {% block css %}
      <!-- Latest compiled and minified Bootstrap 4 Alpha 4 CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

      <!-- Your stuff: Third-party CSS libraries go here -->

      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

      <!-- This file stores project-specific CSS -->
      <link rel="stylesheet/less" type="text/css" href="{% static 'less/base.less' %}" />
      <link rel="stylesheet/less" type="text/css" href="{% static 'less/users.less' %}" />
      <link href="https://fonts.googleapis.com/css?family=Didact+Gothic&amp;subset=latin-ext" rel="stylesheet">
      {% endblock %}

    </head>

    <body>

      <div class="container" id="sushi-wrapper">
        <nav class="navbar navbar-toggleable-md navbar-default navigation-clean-search">
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar-items" aria-controls="navbar-items" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fa fa-bars"></i>
          </button>
          <a class="navbar-brand navbar-link" href="{% url 'home' %}"><img src="{% static 'images/sushi.png' %}" id="sushi-icon">Sushi Bar</a>
          <div class="collapse navbar-collapse" id="navbar-items">
            <form id="search-form" class="form-inline">
              <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                <input type="text" class="form-control typeahead" placeholder="Search..." aria-label="Search" aria-describedby="search-icon" id="search-input">
                <span class="input-group-addon" id="search-icon"><i class="fa fa-search"></i></span>
              </div>
            </form>
            <ul class="nav navbar-nav ml-auto w-100 justify-content-end">
              {% if request.user.is_authenticated %}
              <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="true" href="#">{{ request.user.username }}<span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li role="presentation">
                    <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
                  </li>
                  <li role="presentation">
                    <a class="nav-link" href="{% url 'sushibar_signout' %}">Sign out</a>
                  </li>
                </ul>
              </li>
              {% else %}
              <li class="nav-item">
                {# URL provided by sushibar/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'sushibar_signin' %}">{% trans "Sign In" %}</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </nav>
          {% if messages %}
          {% for message in messages %}
          <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
          {% endif %}

          {% block content %}
          <p>Use this document as a way to quick start any new project.</p>
          {% endblock content %}
        <div class="footer-basic">
          <hr>
          <footer>
              <a href="http://contentworkshop.learningequality.org" target="_blank">Kolibri Studio&nbsp;·</a>
              <a href="https://github.com/learningequality/ricecooker" target="_blank">&nbsp;Ricecooker&nbsp;·</a>
              <a href="https://github.com/learningequality/sushibar" target="_blank">&nbsp;Github</a>
              <p class="copyright"><a href="https://learningequality.org" target="_blank">Learning Equality © 2017</a></p>
          </footer>
        </div>
      </div>

      {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
    <!-- Required by Bootstrap v4 Alpha 4 -->
    <script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

    <!-- Your stuff: Third-party javascript libraries go here -->
    <script src="{% static 'js/typeahead.bundle.min.js' %}"></script>

    <!-- place project specific Javascript in this file -->

    <script src="{% static 'js/project.js' %}"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/less.js/2.7.2/less.min.js"></script>
    {% endblock javascript %}
  </body>
  </html>